version: 2.1
orbs:
  node: circleci/node@5.0.3
  cypress: cypress-io/cypress@1
jobs:
  cypress/run:
    steps:
      - run:
        command: 'npm install'
workflows:
  build:
    jobs:
      - cypress/run:
          start: 'npm start'
